src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $lead = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created_at = null;

    #[ORM\OneToMany(targetEntity: 'Comment', mappedBy: "post", cascade: ['remove'])]

    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->created_at = new \DateTime('now');
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(string $id): ?int
    {
        return $this->id;

    
    }


    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getLead(): ?string
    {
        return $this->lead;
    }

    public function setLead(?string $lead): static
    {
        $this->lead = $lead;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Attribute\Route;

// Include paginator interface
use Knp\Component\Pager\PaginatorInterface;


class DefaultController extends AbstractController
{

    #[Route('/', name: 'homepage')]
    public function index(Request $request, EntityManagerInterface $em,  PaginatorInterface $paginator): Response
    {   

        // Get from database
        $posts = $em->createQueryBuilder()
        ->select('P')
        ->from(Post::class, 'P')
        ->orderBy('P.created_at', 'DESC')
        ->getQuery()
        ->getResult();
     
        // Use paginator
        $pagination = $paginator->paginate($posts,$request->query->getInt('page', 1),10);


        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
            'posts' => $pagination
        ]);
    }

    #[Route("/atrykul/{id}", name: "post_show" )]
    public function show(Post $post,EntityManagerInterface $em, Request $request) {

        $form = null;

        //Add comment to user if user is logged
        if($user = $this->getUser()) {
            //Create new comment object
            $comment = new Comment();
            //Add comment to post
            $comment->setPost($post);
            $comment->setUser($user);

            // Create comment form
            $form = $this->createForm(CommentType::class, $comment);


            $form->handleRequest($request);

            if($form->isSubmitted() && $form->isValid()) {
                $em->persist($comment);
                $em->flush();

                $this->addFlash('success', "Komentarz został dodany.");

            return $this->redirectToRoute('post_show', ['id' => $post->getId()]);
        }
        }
        

  

        return $this->render('default/show.html.twig', [
            'post' => $post,
            'form' => is_null($form) ? $form : $form->createView()
        ]);
    }


}

templates/default/index.html.twig
{% extends 'base.html.twig' %}


{% block title %}Blog{% endblock %}

{% block body %}

<h1>Hello blog!</h1>

{% for post in posts %}

    <div>
        <h2><a href="{{ path('post_show', {'id': post.id}) }}">{{ post.title }}</a></h2>

        <p>{{ post.lead }}</p>
    
    </div>
    
{% endfor %}

<div class="navigation">
            {{ knp_pagination_render(posts) }}
</div>

{% endblock %}

templates/default/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Artykuł{% endblock %}

{% block body %}

<h1> {{ post.title }}</h1>

<p>{{ post.lead }}</p>
<p>{{ post.content|raw }}</p>

<p class="text-end">Dodano: {{ post.createdAt|date("H:i d/m/Y") }}</p>

<hr>

<h3>Komentarze</h3>

{% if app.user %}

{{ form_start(form )}}

{{ form_widget(form)}}

<button class="btn btn-primary float-end" type="submit">Dodaj komentarz</button>

{{ form_end(form)}}

{% else %}
    
    <p>Dodawanie komentarzy tylko dla zalogownych użytkowników. <a href="{{ path('app_login') }}">Zaloguj się</a></p>

{% endif %}



<div class="col-6">
{% for comment in post.comments %}

    <div class="card my-2 p-2">
        <p>{{ comment.content }}</p>
        <p class="text-end text-muted">Dodano: {{ comment.createdAt|date("H:i d/m/Y") }} przez: {% if comment.user %} {{ comment.user.email }}{% endif %} </p> 
        
        
    
    </div>
    
{% endfor %}

<div>



{% endblock %}